### ISSUE TITLE
User credentials

### ISSUE THREAD

**Issue by psstoyanov** [capyloon/mobian-recipes#2]
Built an image against `capyloon` branch for the PinePhone.

The credentials in the [README.md](https://github.com/capyloon/mobian-recipes/blob/121cefe6245528b77794d63adff182bdeaf5c25f/README.md?plain=1#L8) didn't work. But using `capyloon` for the user did the trick.

**Comment by arky** [comment]
@@fabricedesre  To resolve this issue perhaps we can make the 'capyloon' branch the main for this repo. We could update the reflect the default capyloon usernames and passwords.

**Comment by fabricedesre** [comment]
Good points. I switched the default branch and updated the Readme to the correct default username in https://github.com/capyloon/mobian-recipes/commit/8e329948aadbba1dae063f30f1dc4fb3e0d7e601
